name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: linux-deploy
          path: ./app/build/outputs/apk/release

  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: gradle/wrapper-validation-action@v1

